"""Initial migrate

Revision ID: 63b266f391d3
Revises: 
Create Date: 2025-12-12 00:52:50.803827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63b266f391d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field_changed', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('old_value', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('new_value', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('assessment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('assessment_history_changed_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['changed_by'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('old_score')
        batch_op.drop_column('new_score')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_manager'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['manager_id'], ['id'])

    with op.batch_alter_table('skill_assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(batch_op.f('skill_assessments_user_id_skill_id_key'), type_='unique')
        batch_op.create_unique_constraint('unique_user_skill', ['user_id', 'skill_id'])

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(batch_op.f('users_department_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('users_department_id_fkey'), 'departments', ['department_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('skill_assessments', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_skill', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('skill_assessments_user_id_skill_id_key'), ['user_id', 'skill_id'])
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_manager'), 'users', ['manager_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('assessment_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_score', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('old_score', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('assessment_history_changed_by_fkey'), 'users', ['changed_by'], ['id'])
        batch_op.alter_column('assessment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('notes')
        batch_op.drop_column('new_value')
        batch_op.drop_column('old_value')
        batch_op.drop_column('field_changed')

    # ### end Alembic commands ###
